### ISSUE TITLE
Ability to create categories

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/sparked-next#115]
These will be used to categorize contents. 

e.g:

- Text Books
- Syllabus
- Supplementary videos
- Stem Power
- Simulated Laboratory Videos
- Reference Books
- Laboratories
- Human Anatomy
- ESTP (Grade 11 And 12 Revision)
- Educational Plasma Programs
- Addis Ababa Education Bureau

**Comment by brianmuks** [comment]
> @brianmuks we really need this

@OlivierJM now working on this.
