### ISSUE TITLE
Replace primitive fetch with SWR/SSR across the code 

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/sparked-next#60]
I have noticed that we are not taking advantages of the best features that nextjs offers from the alternatives and because of this we lose out on performance. 

So for pages that don't need realtime data or any type of immediate refetch, example user facing pages where we load either topics and their resources, we should use server side rendering ref: https://nextjs.org/docs/pages/building-your-application/rendering/server-side-rendering or SSG depending on what works best for our use case https://nextjs.org/docs/pages/building-your-application/rendering/static-site-generation
This will simplify our code and make pages render faster and smoother. 

For dashboard pages where we need to refetch the same information after certain actions, we should use CSR https://nextjs.org/docs/pages/building-your-application/rendering/client-side-rendering (scroll down to swr) direct link here https://swr.vercel.app 

ref: https://swr.vercel.app/docs/with-nextjs
With this we will have automatic caching and faster performance for our pages.

**Comment by YewoMhango** [comment]
@OlivierJM I have started by working on #71, so yeah, you can help me with this one
